version: '3'
services:
  upload:
    container_name: upload
    build: ./src/services/upload
    ports:
      - "3000:3000"
    volumes:
      - './src/services/upload:/app'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: exit 0
